version: '3'
services:
  back:
    container_name: my_back_container
    build:
      context: .
      dockerfile: back.Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - webLab
  front:
    container_name: my_front_container
    build:
      context: .
      dockerfile: front.Dockerfile
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - webLab
networks:
  webLab:
